<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <AkkaVersion>1.5.60</AkkaVersion>
    <MSTestVersion>3.0.2</MSTestVersion>
    <TestSdkVersion>17.5.0</TestSdkVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.TestKit" Version="$(AkkaVersion)" />
    <PackageVersion Include="MSTest.TestFramework" Version="$(MSTestVersion)" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageVersion Include="MSTest.TestAdapter" Version="$(MSTestVersion)" />
    <PackageVersion Include="coverlet.collector" Version="3.2.0" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
  </ItemGroup>
</Project>
