<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <AkkaVersion>1.5.67</AkkaVersion>
    <MSTest4Version>4.1.0</MSTest4Version>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.TestKit" Version="$(AkkaVersion)" />
    <PackageVersion Include="MSTest.TestFramework" Version="$(MSTest4Version)" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
  </ItemGroup>
</Project>
