<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TestFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.TestKit.MsTest\Akka.TestKit.MsTest.csproj" />
  </ItemGroup>

</Project>
