// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Akka.NET Contrib")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2013-2017 Akka.NET Contrib")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.3.2.0")]
[assembly: AssemblyFileVersionAttribute("1.3.2.0")]
